"use client";

import { useEffect, useRef, useState } from "react";

// Per-gate approve button labels
const APPROVE_LABELS: Record<string, string> = {
  review_requirements:    "Approve Requirements",
  review_hls:             "Approve Scenarios",
  review_tcs:             "Approve Test Cases",
  review_coverage:        "Approve Coverage",
  review_jira:            "Write to JIRA →",
  review_classifications: "Approve Classifications",
  review_scripts:         "Approve Scripts",
  review_report:          "Approve Report",
};

interface GateActionBarProps {
  gate: string;
  editMode: boolean;
  featureSlug?: string | null;
  onEditModeToggle: () => void;
  onApprove: (projectName?: string) => void;
  onReject: (feedback: string) => void;
  draftSaved?: boolean;
  onSaveDraft?: () => void;
  onEditAgain?: () => void;
}

export default function GateActionBar({
  gate,
  editMode,
  featureSlug,
  onEditModeToggle,
  onApprove,
  onReject,
  draftSaved,
  onSaveDraft,
  onEditAgain,
}: GateActionBarProps) {
  const [showReject, setShowReject] = useState(false);
  const [rejectText, setRejectText] = useState("");

  const [projectName, setProjectName] = useState("");
  const [projects, setProjects] = useState<string[]>([]);
  const [showDropdown, setShowDropdown] = useState(false);
  const [projectNameWarning, setProjectNameWarning] = useState("");
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const isScriptsGate = gate === "review_scripts";
  const isReqsGate    = gate === "review_requirements";
  const approveLabel  = APPROVE_LABELS[gate] ?? "Approve";
  const gateLabel     = gate.replace(/^review_/, "").replace(/_/g, " ").toUpperCase();

  // Save Draft replaces "Approve with edits" when onSaveDraft is wired; Approve is the final action
  const isSaveDraftMode = editMode && !!onSaveDraft;
  const isDraftApproveMode = !!draftSaved && !editMode;

  async function fetchProjects(): Promise<string[]> {
    try {
      const res = await fetch("/api/projects");
      if (res.ok) {
        const data = await res.json();
        const list: string[] = data.projects ?? [];
        setProjects(list);
        return list;
      }
    } catch {
      // non-fatal
    }
    return [];
  }

  // Auto-generate project name on mount if at review_scripts gate
  useEffect(() => {
    if (!isScriptsGate || projectName) return;
    (async () => {
      const list = await fetchProjects();
      const base = (featureSlug || "project").toLowerCase().trim().replace(/[^a-z0-9-]/g, "-") || "project";
      const matching = list.filter((p) => p === base || p.startsWith(`${base}-v`));
      const version = matching.length + 1;
      const generated = version === 1 && !list.includes(base) ? base : `${base}-v${version}`;
      setProjectName(generated);
      setIsAutoGenerated(true);
    })();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isScriptsGate]);

  useEffect(() => {
    if (!isScriptsGate) return;
    if (projectName.length >= 2) {
      fetchProjects();
      setShowDropdown(true);
    } else {
      setShowDropdown(false);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectName, isScriptsGate]);

  useEffect(() => {
    function handleOutside(e: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setShowDropdown(false);
      }
    }
    document.addEventListener("mousedown", handleOutside);
    return () => document.removeEventListener("mousedown", handleOutside);
  }, []);

  const filteredProjects = projects.filter((p) =>
    p.toLowerCase().includes(projectName.toLowerCase())
  );
  const isExistingProject = projectName.length > 0 && projects.includes(projectName);
  const isNewProject = projectName.length > 0 && !projects.includes(projectName);

  function handleRejectConfirm() {
    onReject(rejectText);
    setShowReject(false);
    setRejectText("");
  }

  function handleApproveClick() {
    // Save Draft path — requirements gate in edit mode
    if (isSaveDraftMode) {
      onSaveDraft!();
      return;
    }
    // Normal approve path
    if (isScriptsGate && !projectName.trim()) {
      setProjectNameWarning("No project name entered — scripts will be saved under default");
    } else {
      setProjectNameWarning("");
    }
    onApprove(isScriptsGate ? projectName.trim() || undefined : undefined);
  }

  // Approve button label and style
  let approveBtnLabel: string;
  let approveBtnStyle: React.CSSProperties;
  if (isSaveDraftMode) {
    approveBtnLabel = "Save Draft";
    approveBtnStyle = {
      background: "linear-gradient(135deg, #f59e0b, #d97706)",
      color: "#fff",
      boxShadow: "0 2px 12px rgba(245,158,11,0.3)",
    };
  } else if (isDraftApproveMode) {
    approveBtnLabel = "Approve";
    approveBtnStyle = {
      background: "linear-gradient(135deg, #22c55e, #16a34a)",
      color: "#fff",
      boxShadow: "0 2px 12px rgba(34,197,94,0.3)",
    };
  } else {
    approveBtnLabel = editMode ? "Approve with edits" : approveLabel;
    approveBtnStyle = {
      background: "linear-gradient(135deg, #1dc8b8, #0fb3a4)",
      color: "#fff",
      boxShadow: "0 2px 12px rgba(29,200,184,0.3)",
    };
  }

  return (
    <div
      className="shrink-0 flex flex-col"
      style={{
        background: "rgba(7,13,24,0.97)",
        borderTop: "1px solid rgba(255,255,255,0.07)",
      }}
    >
      {/* Reject panel — expands above action row */}
      {showReject && (
        <div
          className="flex flex-col gap-3 px-6 py-4 animate-fade-up"
          style={{ borderBottom: "1px solid rgba(239,68,68,0.15)" }}
        >
          <label className="text-xs font-medium text-muted">
            Reject reason — feedback will be stored and injected into future runs:
          </label>
          <textarea
            className="w-full rounded-lg px-3 py-2.5 text-sm text-text placeholder-muted/40 focus:outline-none resize-none"
            style={{
              background: "rgba(14,23,38,0.8)",
              border: "1px solid rgba(239,68,68,0.3)",
            }}
            rows={3}
            placeholder="Describe what was wrong and how to improve..."
            value={rejectText}
            onChange={(e) => setRejectText(e.target.value)}
            autoFocus
            onFocus={(e) => { e.currentTarget.style.borderColor = "rgba(239,68,68,0.6)"; }}
            onBlur={(e) => { e.currentTarget.style.borderColor = "rgba(239,68,68,0.3)"; }}
          />
          <div className="flex gap-2 justify-end">
            <button
              onClick={() => { setShowReject(false); setRejectText(""); }}
              className="px-4 py-1.5 text-sm rounded-lg transition-colors"
              style={{ background: "transparent", border: "1px solid rgba(255,255,255,0.1)", color: "#8896a8" }}
            >
              Cancel
            </button>
            <button
              onClick={handleRejectConfirm}
              disabled={!rejectText.trim()}
              className="px-4 py-1.5 text-sm font-semibold rounded-lg transition-all disabled:opacity-30"
              style={{ background: "#ef4444", color: "#fff" }}
            >
              Confirm Reject
            </button>
          </div>
        </div>
      )}

      {/* Project name input — only at review_scripts */}
      {isScriptsGate && (
        <div className="px-6 pt-4 pb-2 flex flex-col gap-1.5">
          <label className="text-xs font-medium text-muted">Project Name</label>
          <div className="relative w-full max-w-sm" ref={dropdownRef}>
            <input
              type="text"
              className="w-full rounded-lg px-3 py-2 text-sm text-text placeholder-muted/40 focus:outline-none transition-colors"
              style={{
                background: "rgba(11,18,32,0.8)",
                border: "1px solid rgba(255,255,255,0.07)",
              }}
              placeholder="e.g. dubai-justice-portal"
              value={projectName}
              onChange={(e) => { setProjectName(e.target.value); setProjectNameWarning(""); setIsAutoGenerated(false); }}
              onFocus={(e) => {
                e.currentTarget.style.borderColor = "rgba(29,200,184,0.4)";
                fetchProjects();
                if (projectName.length >= 2) setShowDropdown(true);
              }}
              onBlur={(e) => { e.currentTarget.style.borderColor = "rgba(255,255,255,0.07)"; }}
            />
            {showDropdown && filteredProjects.length > 0 && (
              <div
                className="absolute z-10 top-full mt-1 w-full rounded-lg overflow-hidden"
                style={{ background: "#0e1726", border: "1px solid rgba(255,255,255,0.07)", boxShadow: "0 8px 24px rgba(0,0,0,0.5)" }}
              >
                {filteredProjects.map((p) => (
                  <button
                    key={p}
                    className="w-full text-left px-3 py-2 text-sm text-text transition-colors"
                    style={{ borderBottom: "1px solid rgba(255,255,255,0.04)" }}
                    onMouseDown={(e) => { e.preventDefault(); setProjectName(p); setShowDropdown(false); }}
                    onMouseEnter={(e) => { e.currentTarget.style.background = "rgba(29,200,184,0.08)"; }}
                    onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; }}
                  >
                    {p}
                  </button>
                ))}
              </div>
            )}
          </div>
          {isAutoGenerated && (
            <span
              className="text-xs font-medium px-2 py-0.5 rounded self-start"
              style={{ background: "rgba(157,110,247,0.15)", color: "#9d6ef7", border: "1px solid rgba(157,110,247,0.25)" }}
            >
              ⚡ Auto-generated
            </span>
          )}
          {!isAutoGenerated && isExistingProject && (
            <span className="text-xs font-medium" style={{ color: "#1dc8b8" }}>✓ Existing project — scripts will be appended</span>
          )}
          {!isAutoGenerated && isNewProject && (
            <span className="text-xs font-medium" style={{ color: "#38bdf8" }}>+ New project will be created</span>
          )}
          {projectNameWarning && (
            <span className="text-xs" style={{ color: "#f59e0b" }}>{projectNameWarning}</span>
          )}
        </div>
      )}

      {/* Main 64px action row */}
      <div className="flex items-center justify-between px-6 h-16 gap-4">
        <div className="flex items-center gap-2">
          <div
            className="w-1.5 h-1.5 rounded-full animate-pulse"
            style={{ background: isDraftApproveMode ? "#f59e0b" : "#1dc8b8" }}
          />
          <span className="text-[11px] font-mono tracking-widest" style={{ color: "#8896a8" }}>
            {isDraftApproveMode ? "DRAFT SAVED · " : "AWAITING REVIEW · "}{gateLabel}
          </span>
        </div>

        <div className="flex items-center gap-2">
          {/* Edit button — hidden in draft-approve mode (Edit Again serves this role) */}
          {!isDraftApproveMode && (
            <button
              onClick={onEditModeToggle}
              className="flex items-center gap-1.5 transition-all"
              style={{
                background: editMode ? "rgba(29,200,184,0.25)" : "rgba(29,200,184,0.15)",
                border: `1px solid ${editMode ? "rgba(29,200,184,0.5)" : "rgba(29,200,184,0.4)"}`,
                color: "#1dc8b8",
                padding: "6px 12px",
                borderRadius: 6,
              }}
              onMouseEnter={(e) => { e.currentTarget.style.background = "rgba(29,200,184,0.25)"; }}
              onMouseLeave={(e) => { e.currentTarget.style.background = editMode ? "rgba(29,200,184,0.25)" : "rgba(29,200,184,0.15)"; }}
            >
              <svg className="w-3.5 h-3.5" viewBox="0 0 20 20" fill="currentColor">
                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
              </svg>
              <span className="text-xs font-medium">{editMode ? "Editing" : "Edit"}</span>
            </button>
          )}

          {/* Edit Again — only in draft-approve mode */}
          {isDraftApproveMode && onEditAgain && (
            <button
              onClick={onEditAgain}
              className="flex items-center gap-1.5 transition-all"
              style={{
                background: "rgba(29,200,184,0.12)",
                border: "1px solid rgba(29,200,184,0.3)",
                color: "#1dc8b8",
                padding: "6px 12px",
                borderRadius: 6,
              }}
              onMouseEnter={(e) => { e.currentTarget.style.background = "rgba(29,200,184,0.22)"; }}
              onMouseLeave={(e) => { e.currentTarget.style.background = "rgba(29,200,184,0.12)"; }}
            >
              <svg className="w-3.5 h-3.5" viewBox="0 0 20 20" fill="currentColor">
                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
              </svg>
              <span className="text-xs font-medium">Edit Again</span>
            </button>
          )}

          <button
            onClick={() => setShowReject((s) => !s)}
            className="px-4 py-1.5 text-sm font-semibold rounded-lg transition-all"
            style={
              showReject
                ? { background: "rgba(239,68,68,0.18)", color: "#ef4444", border: "1px solid rgba(239,68,68,0.35)" }
                : { background: "rgba(239,68,68,0.1)", color: "#ef4444", border: "1px solid rgba(239,68,68,0.2)" }
            }
            onMouseEnter={(e) => { if (!showReject) e.currentTarget.style.background = "rgba(239,68,68,0.18)"; }}
            onMouseLeave={(e) => { if (!showReject) e.currentTarget.style.background = "rgba(239,68,68,0.1)"; }}
          >
            Reject
          </button>

          <button
            onClick={handleApproveClick}
            className="px-4 py-1.5 text-sm font-semibold rounded-lg transition-all"
            style={approveBtnStyle}
            onMouseEnter={(e) => { e.currentTarget.style.opacity = "0.85"; }}
            onMouseLeave={(e) => { e.currentTarget.style.opacity = "1"; }}
          >
            {approveBtnLabel}
          </button>
        </div>
      </div>
    </div>
  );
}
