import os
import time
from typing import Optional

import httpx

from agent.node_logger import compute_input_hash, log_node_event
from graph.state import AgentState


def _gh_headers() -> dict[str, str]:
    token = os.getenv("GITHUB_PERSONAL_ACCESS_TOKEN", "")
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _gh_repo() -> str:
    return os.getenv("GITHUB_REPO", "")


def _build_pr_body(state: AgentState, coverage_pct: float) -> str:
    tc_list = state.get("tc_list") or []
    tc_classifications = state.get("tc_classifications") or []
    execution_results = state.get("execution_results") or []

    automated_ids = {c["tc_id"] for c in tc_classifications if c.get("mode") == "automated"}
    titles = {tc["id"]: tc.get("title", "") for tc in tc_list}
    results_by_tc = {r["tc_id"]: r for r in execution_results}

    rows = ["| TC ID | Title | Status |", "|-------|-------|--------|"]
    for tc_id in sorted(automated_ids):
        result = results_by_tc.get(tc_id)
        status = (result or {}).get("status", "not_run")
        badge = "✅" if status == "passed" else ("❌" if status == "failed" else "⏭")
        rows.append(f"| `{tc_id}` | {titles.get(tc_id, '')} | {badge} {status} |")

    table = "\n".join(rows)
    return (
        f"## SDET Agent Results\n\n"
        f"**Ticket:** `{state['ticket_id']}`  \n"
        f"**Run ID:** `{state['run_id']}`  \n"
        f"**Coverage:** {coverage_pct:.1f}%\n\n"
        f"{table}\n\n"
        f"_Generated by SDET Multi-Agent Pipeline v1.1_"
    )


async def commit_github_node(state: AgentState) -> AgentState:
    t0 = time.monotonic()
    run_id = state["run_id"]
    ticket_id = state["ticket_id"]
    repo = _gh_repo()
    branch = f"sdet-agent/{run_id}"
    input_hash = compute_input_hash({"run_id": run_id, "ticket_id": ticket_id})

    report = state.get("report") or {}
    coverage_pct = float(report.get("coverage_percentage", 0.0))

    if not (repo and os.getenv("GITHUB_PERSONAL_ACCESS_TOKEN")):
        error_msg = "GitHub credentials not configured — set GITHUB_REPO and GITHUB_PERSONAL_ACCESS_TOKEN"
        await log_node_event(
            run_id=run_id, node="commit_github", attempt=0, provider="github_rest",
            input_hash=input_hash, output_json={}, latency_ms=0, error=error_msg,
        )
        return {**state, "error": error_msg}

    title = f"chore(sdet): SDET agent results for {ticket_id} [{run_id[:8]}]"
    body = _build_pr_body(state, coverage_pct)
    owner = repo.split("/")[0] if "/" in repo else repo

    pr_url: Optional[str] = None
    pr_number: Optional[int] = None
    action: str = "skipped"

    async with httpx.AsyncClient(timeout=30.0) as client:
        # Check whether a PR already exists for this branch
        list_resp = await client.get(
            f"https://api.github.com/repos/{repo}/pulls",
            headers=_gh_headers(),
            params={"state": "open", "head": f"{owner}:{branch}"},
        )
        list_resp.raise_for_status()
        existing = list_resp.json()

        if existing:
            pr_number = existing[0]["number"]
            patch_resp = await client.patch(
                f"https://api.github.com/repos/{repo}/pulls/{pr_number}",
                headers=_gh_headers(),
                json={"body": body},
            )
            patch_resp.raise_for_status()
            pr_url = patch_resp.json()["html_url"]
            action = "updated"
        else:
            default_branch = os.getenv("GITHUB_DEFAULT_BRANCH", "main")
            create_resp = await client.post(
                f"https://api.github.com/repos/{repo}/pulls",
                headers=_gh_headers(),
                json={
                    "title": title,
                    "body": body,
                    "head": branch,
                    "base": default_branch,
                    "draft": False,
                },
            )
            create_resp.raise_for_status()
            data = create_resp.json()
            pr_url = data["html_url"]
            pr_number = data["number"]
            action = "created"

    # Store PR URL in report so send_email_node can reference it
    updated_report = {**report, "pr_url": pr_url}

    latency_ms = int((time.monotonic() - t0) * 1000)
    await log_node_event(
        run_id=run_id,
        node="commit_github",
        attempt=0,
        provider="github_rest",
        input_hash=input_hash,
        output_json={"action": action, "pr_number": pr_number, "pr_url": pr_url},
        latency_ms=latency_ms,
        error=None,
    )

    return {**state, "report": updated_report}
