import json
import re
import time

from pydantic import ValidationError  # noqa: F401 — propagates through with_retry

from agent.node_logger import compute_input_hash, log_node_event
from agent.provider import run_agent
from agent.retry import with_retry
from agent.schemas import HLSItem, HLSOutput
from graph.state import AgentState

_SYSTEM = (
    "You are an expert SDET test architect. "
    "Generate High-Level Scenarios (HLS) from structured requirements. "
    "Return ONLY valid JSON — no markdown fences, no explanation."
)

# System-owned sentinel — always appended last, never generated by the LLM.
_HLS_EXP: dict = {
    "id": "HLS-EXP",
    "title": "Exploratory Testing",
    "description": "Catch-all for exploratory TCs with no specific requirement link.",
    "linked_requirements": [],
    "type": "exploratory",
}


# ── Prompt builders ────────────────────────────────────────────────────────────

def _build_full_prompt(requirements_analysis: dict) -> str:
    reqs = requirements_analysis.get("requirements", [])
    req_lines = "\n".join(f"  {r['id']}: {r['text']}" for r in reqs)
    return f"""Generate High-Level Scenarios (HLS) from these requirements.

REQUIREMENTS:
{req_lines}

Return JSON matching this exact schema (no extra keys, no markdown):
{{
  "hls_list": [
    {{
      "id": "HLS-001",
      "title": "<one clear user flow>",
      "description": "<what this scenario tests>",
      "linked_requirements": ["REQ-001"],
      "type": "<positive|negative|edge|exploratory>"
    }}
  ]
}}

Rules:
- Sequential IDs: HLS-001, HLS-002, HLS-003 …
- Each HLS represents ONE clear user flow
- Each HLS MUST link to at least one REQ ID from the list above
- type must be one of: positive | negative | edge | exploratory
- Do NOT generate id="HLS-EXP" — the system appends it automatically
- Cover positive, negative, edge-case, and boundary paths
"""


def _build_diff_prompt(
    requirements_analysis: dict, existing_hls: list, changed_ids: list
) -> str:
    reqs = requirements_analysis.get("requirements", [])
    req_lines = "\n".join(f"  {r['id']}: {r['text']}" for r in reqs)
    preserved = [
        h for h in existing_hls
        if h.get("id") not in changed_ids and h.get("id") != "HLS-EXP"
    ]
    preserved_lines = "\n".join(
        f"  {h['id']}: {h['title']} (links: {h.get('linked_requirements', [])})"
        for h in preserved
    ) or "  (none)"
    return f"""Regenerate ONLY these HLS items: {changed_ids}

REQUIREMENTS:
{req_lines}

PRESERVED (do NOT include in output):
{preserved_lines}

Return JSON containing ONLY the items being regenerated:
{{
  "hls_list": [
    {{
      "id": "HLS-002",
      "title": "<one clear user flow>",
      "description": "<what this scenario tests>",
      "linked_requirements": ["REQ-001"],
      "type": "<positive|negative|edge|exploratory>"
    }}
  ]
}}

Rules:
- Output ONLY items whose IDs are in: {changed_ids}
- Each item MUST link to at least one REQ ID
- type must be one of: positive | negative | edge | exploratory
- Do NOT include id="HLS-EXP"
"""


# ── Helpers ────────────────────────────────────────────────────────────────────

def _strip_fences(raw: str) -> str:
    cleaned = re.sub(r"```(?:json)?\s*", "", raw).strip().rstrip("`").strip()
    if not cleaned.startswith("{"):
        m = re.search(r"\{.*\}", cleaned, re.DOTALL)
        if m:
            cleaned = m.group()
    return cleaned


def _validate_req_links(items: list[HLSItem]) -> None:
    """Every non-HLS-EXP item must link to at least one REQ (ValueError → retry)."""
    bad = [h.id for h in items if h.id != "HLS-EXP" and not h.linked_requirements]
    if bad:
        raise ValueError(f"HLS items missing linked_requirements: {bad}")


def _hls_sort_key(hls_id: str) -> tuple:
    parts = hls_id.split("-")
    try:
        return (0, int(parts[-1]))
    except (ValueError, IndexError):
        return (1, hls_id)


def _append_hls_exp(items: list[dict]) -> list[dict]:
    """Strip any LLM-generated HLS-EXP then append the system-owned version last."""
    return [h for h in items if h.get("id") != "HLS-EXP"] + [_HLS_EXP]


# ── Node ───────────────────────────────────────────────────────────────────────

async def generate_hls_node(state: AgentState) -> AgentState:
    t0 = time.monotonic()
    requirements_analysis = state.get("requirements_analysis") or {}
    changed_ids: list = state.get("changed_hls_ids") or []
    diff_mode = bool(changed_ids)
    start_retries = state.get("hls_retry_count", 0)
    input_hash = compute_input_hash({
        "requirements_analysis": requirements_analysis,
        "changed_hls_ids": changed_ids,
    })

    async def _generate(s: AgentState) -> AgentState:
        req_analysis = s.get("requirements_analysis") or {}
        c_ids: list = s.get("changed_hls_ids") or []

        if diff_mode:
            prompt = _build_diff_prompt(req_analysis, s.get("hls_list") or [], c_ids)
        else:
            prompt = _build_full_prompt(req_analysis)

        raw = await run_agent(
            prompt=prompt,
            provider=s["provider"],
            system=_SYSTEM,
            calling_node="generate_hls_node",
        )

        parsed = json.loads(_strip_fences(raw))
        validated = HLSOutput(**parsed)       # ValidationError → retry
        _validate_req_links(validated.hls_list)  # ValueError → retry

        new_items = [h.model_dump() for h in validated.hls_list]

        if diff_mode:
            existing = s.get("hls_list") or []
            preserved = {
                h["id"]: h for h in existing
                if h.get("id") not in c_ids and h.get("id") != "HLS-EXP"
            }
            # Only keep items the LLM was asked to regenerate (discard any extras)
            regenerated = {h["id"]: h for h in new_items if h["id"] in c_ids}
            merged = {**preserved, **regenerated}
            sorted_items = sorted(merged.values(), key=lambda h: _hls_sort_key(h["id"]))
            final = _append_hls_exp(sorted_items)
        else:
            final = _append_hls_exp(new_items)

        return {**s, "hls_list": final}

    result = await with_retry(_generate, state, retry_key="hls_retry_count")

    latency_ms = int((time.monotonic() - t0) * 1000)
    await log_node_event(
        run_id=state["run_id"],
        node="generate_hls",
        attempt=result.get("hls_retry_count", 0) - start_retries,
        provider=state["provider"],
        input_hash=input_hash,
        output_json={"hls_list": result.get("hls_list") or []},
        latency_ms=latency_ms,
        error=result.get("error"),
    )

    return result
